name: build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - 
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Build x86_64 container image into library
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          load: true
          push: false
          platforms: linux/amd64
          build-args: |
            VERSION=latest-dev
            GIT_COMMIT=${{ github.sha }}
          tags: |
            ghcr.io/openfaas/queue-worker:${{ github.sha }}
      - 
        name: Build multi-arch container images (for validation only)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          load: false
          push: false
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          build-args: |
            VERSION=latest-dev
            GIT_COMMIT=${{ github.sha }}
          tags: |
            ghcr.io/openfaas/queue-worker:${{ github.sha }}
